// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ProbeMapEvents                 = "events"
	ProbeMapTargetPidMap           = "target_pid_map"
	ProbeProgTraceInetSockSetState = "trace_inet_sock_set_state"
	ProbeProgTraceOomMarkVictim    = "trace_oom_mark_victim"
	ProbeProgTraceSysBpf           = "trace_sys_bpf"
	ProbeProgTraceSysExecve        = "trace_sys_execve"
	ProbeProgTraceSysFinitModule   = "trace_sys_finit_module"
	ProbeProgTraceSysInitModule    = "trace_sys_init_module"
	ProbeProgTraceSysKill          = "trace_sys_kill"
	ProbeProgTraceSysMount         = "trace_sys_mount"
	ProbeProgTraceSysOpenat        = "trace_sys_openat"
	ProbeProgTraceSysSetuid        = "trace_sys_setuid"
	ProbeProgTraceSysUnlinkat      = "trace_sys_unlinkat"
	ProbeVarUnusedBpf              = "unused_bpf"
	ProbeVarUnusedExec             = "unused_exec"
	ProbeVarUnusedModule           = "unused_module"
	ProbeVarUnusedMount            = "unused_mount"
	ProbeVarUnusedNet              = "unused_net"
	ProbeVarUnusedOom              = "unused_oom"
	ProbeVarUnusedOpen             = "unused_open"
	ProbeVarUnusedSetuid           = "unused_setuid"
	ProbeVarUnusedSignal           = "unused_signal"
	ProbeVarUnusedUnlink           = "unused_unlink"
)

// LoadProbe returns the embedded CollectionSpec for Probe.
func LoadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Probe: %w", err)
	}

	return spec, err
}

// LoadProbeObjects loads Probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProbeObjects
//	*ProbePrograms
//	*ProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProbeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeSpecs struct {
	ProbeProgramSpecs
	ProbeMapSpecs
	ProbeVariableSpecs
}

// ProbeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceOomMarkVictim    *ebpf.ProgramSpec `ebpf:"trace_oom_mark_victim"`
	TraceSysBpf           *ebpf.ProgramSpec `ebpf:"trace_sys_bpf"`
	TraceSysExecve        *ebpf.ProgramSpec `ebpf:"trace_sys_execve"`
	TraceSysFinitModule   *ebpf.ProgramSpec `ebpf:"trace_sys_finit_module"`
	TraceSysInitModule    *ebpf.ProgramSpec `ebpf:"trace_sys_init_module"`
	TraceSysKill          *ebpf.ProgramSpec `ebpf:"trace_sys_kill"`
	TraceSysMount         *ebpf.ProgramSpec `ebpf:"trace_sys_mount"`
	TraceSysOpenat        *ebpf.ProgramSpec `ebpf:"trace_sys_openat"`
	TraceSysSetuid        *ebpf.ProgramSpec `ebpf:"trace_sys_setuid"`
	TraceSysUnlinkat      *ebpf.ProgramSpec `ebpf:"trace_sys_unlinkat"`
}

// ProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	TargetPidMap *ebpf.MapSpec `ebpf:"target_pid_map"`
}

// ProbeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeVariableSpecs struct {
	UnusedBpf    *ebpf.VariableSpec `ebpf:"unused_bpf"`
	UnusedExec   *ebpf.VariableSpec `ebpf:"unused_exec"`
	UnusedModule *ebpf.VariableSpec `ebpf:"unused_module"`
	UnusedMount  *ebpf.VariableSpec `ebpf:"unused_mount"`
	UnusedNet    *ebpf.VariableSpec `ebpf:"unused_net"`
	UnusedOom    *ebpf.VariableSpec `ebpf:"unused_oom"`
	UnusedOpen   *ebpf.VariableSpec `ebpf:"unused_open"`
	UnusedSetuid *ebpf.VariableSpec `ebpf:"unused_setuid"`
	UnusedSignal *ebpf.VariableSpec `ebpf:"unused_signal"`
	UnusedUnlink *ebpf.VariableSpec `ebpf:"unused_unlink"`
}

// ProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeObjects struct {
	ProbePrograms
	ProbeMaps
	ProbeVariables
}

func (o *ProbeObjects) Close() error {
	return _ProbeClose(
		&o.ProbePrograms,
		&o.ProbeMaps,
	)
}

// ProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	TargetPidMap *ebpf.Map `ebpf:"target_pid_map"`
}

func (m *ProbeMaps) Close() error {
	return _ProbeClose(
		m.Events,
		m.TargetPidMap,
	)
}

// ProbeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeVariables struct {
	UnusedBpf    *ebpf.Variable `ebpf:"unused_bpf"`
	UnusedExec   *ebpf.Variable `ebpf:"unused_exec"`
	UnusedModule *ebpf.Variable `ebpf:"unused_module"`
	UnusedMount  *ebpf.Variable `ebpf:"unused_mount"`
	UnusedNet    *ebpf.Variable `ebpf:"unused_net"`
	UnusedOom    *ebpf.Variable `ebpf:"unused_oom"`
	UnusedOpen   *ebpf.Variable `ebpf:"unused_open"`
	UnusedSetuid *ebpf.Variable `ebpf:"unused_setuid"`
	UnusedSignal *ebpf.Variable `ebpf:"unused_signal"`
	UnusedUnlink *ebpf.Variable `ebpf:"unused_unlink"`
}

// ProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbePrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceOomMarkVictim    *ebpf.Program `ebpf:"trace_oom_mark_victim"`
	TraceSysBpf           *ebpf.Program `ebpf:"trace_sys_bpf"`
	TraceSysExecve        *ebpf.Program `ebpf:"trace_sys_execve"`
	TraceSysFinitModule   *ebpf.Program `ebpf:"trace_sys_finit_module"`
	TraceSysInitModule    *ebpf.Program `ebpf:"trace_sys_init_module"`
	TraceSysKill          *ebpf.Program `ebpf:"trace_sys_kill"`
	TraceSysMount         *ebpf.Program `ebpf:"trace_sys_mount"`
	TraceSysOpenat        *ebpf.Program `ebpf:"trace_sys_openat"`
	TraceSysSetuid        *ebpf.Program `ebpf:"trace_sys_setuid"`
	TraceSysUnlinkat      *ebpf.Program `ebpf:"trace_sys_unlinkat"`
}

func (p *ProbePrograms) Close() error {
	return _ProbeClose(
		p.TraceInetSockSetState,
		p.TraceOomMarkVictim,
		p.TraceSysBpf,
		p.TraceSysExecve,
		p.TraceSysFinitModule,
		p.TraceSysInitModule,
		p.TraceSysKill,
		p.TraceSysMount,
		p.TraceSysOpenat,
		p.TraceSysSetuid,
		p.TraceSysUnlinkat,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfel.o
var _ProbeBytes []byte
